$cd "C:\Program Files (x86)\Steam\steamapps\chemicalalia\team fortress 2\tf\models\player\items\engineer" 
$modelname "player/items/engineer/paper_hat.mdl"
$model "body" "paper_hat_female.smd"
$cdmaterials "models/player/items/all_class/paper_hat"
$hboxset "default"
$hbox 0 "bip_head" -5.751  -10.850  -8.057  5.819  0.000  6.851
// Model uses material "models/player/items/all_class/paper_hat/paper_hat.vmt"
$surfaceprop "default"
$illumposition 1.494 0.034 5.250
$sequence ref "ref" fps 30.00
